name: Eslint

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches: ['master', 'dev']
    # Publish semver tags as releases.
    tags: ['*.*.*']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18.16.0'
          check-latest: true
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run ESLint
        run: |
          yarn lint
